### ISSUE TITLE
No way to know when the client has connected to the server

### ISSUE THREAD

**Issue by ybeaufort** [spacebro/spacebro-client#12]
After connecting with:
```
spacebroClient.connect(host, port, {
  clientName: 'foo',
  channelName: 'bar'
})
```
I need to know when I can start using the client and emit events.

**Comment by emmanuelgeoffray** [comment]
Did you try to use the `connect` event (like in socket-io)
```
spacebroClient.on('connect', (data) => {
  console.log('connected', data)
})
```

**Comment by ybeaufort** [comment]
I tried:
```
spacebroClient.on('connect', () => { console.log('working') })
```
and
```
spacebroClient.on('connection', () => { console.log('working') })
```
but the callback is never called.

I can bypass this problem in my case because I don't use `'new-member'` anywhere else, but I don't think it's a good way to handle it:
```
spacebroClient.once('new-member', () => { console.log('working') })
```

**Comment by gabrielstuff** [comment]
This is now fixed and will be release in v3
