### ISSUE TITLE
Built-in socket.io events should be forwarded

### ISSUE THREAD

**Issue by 4quet** [spacebro/spacebro-client#16]
**spacebro-client** should give some feedback when built-in socket.io events occurs.

Example: if the socket.io `connect` event is forwarded, the user could listen to the `connect` event to know when the **spacebro-client** instance is ready.
```javascript
spacebroClient.on('connect', function() {
  console.log('spacebroClient ready !')
})
```

**Comment by gabrielstuff** [comment]
This is related to https://github.com/spacebro/spacebro-client/issues/12.

We have to forward : 
- [x] Event: 'connect'
- [x] Event: 'connect_error'
- [ ] Event: 'connect_timeout'
- [x] Event: 'error'
- [x] Event: 'disconnect'
- [x] Event: 'reconnect'
- [ ] Event: 'reconnect_attempt'
- [ ] Event: 'reconnecting'
- [ ] Event: 'reconnect_error'
- [ ] Event: 'reconnect_failed'

**Comment by gabrielstuff** [comment]
- [x] Event: 'connect'
- [x] Event: 'connect_error'
- [x] Event: 'connect_timeout'
- [x] Event: 'error'
- [x] Event: 'disconnect'
- [x] Event: 'reconnect'
- [x] Event: 'reconnect_attempt'
- [x] Event: 'reconnecting'
- [x] Event: 'reconnect_error'
- [x] Event: 'reconnect_failed'

**Comment by gabrielstuff** [comment]
Fix with https://github.com/spacebro/spacebro-client/commit/103db715be9cad0d29407d714557ad930077c3f8

**Comment by gabrielstuff** [comment]
All listening on the spacebro client is optionnal
