### ISSUE TITLE
Add a function to disconnect spacebro-client from the server

### ISSUE THREAD

**Issue by ybeaufort** [spacebro/spacebro-client#19]
I would like to be able to disconnect from a spacebro server without having to quit my application.
Just calling `spacebroClient.connect()` doesn't cancel the previous connections.

**Comment by PoignardAzur** [comment]
Pinging this @gabrielstuff. Having something like this would make unit test much easier.

I'm going to look into this and try to refactor spacebro-client to have fewer side-effects without breaking compatibility. I'll push a new branch as soon as possible.
